GET http://localhost:3000/levels/block-builder/ids

###

GET http://localhost:3000/levels

###

GET http://localhost:3000/levels/60c85b253adc7f21c8b38aca


###

POST http://localhost:3000/levels
Content-Type: application/json

{
    "name": "Quincy Taggert",
    "createdBy": "Inversioneer",
    "blueprint": ["1, 2, 3, 4, 5, 6, 7, 8"]
}

###

DELETE http://localhost:3000/levels/60c841ce59df7a1fd437e9d3

###

PATCH http://localhost:3000/levels/60c7e8774fc6d22e24f047f2
Content-Type: application/json

{
    "name": "Heyou, World!",
    "createdBy": "Inversioneer",
    "blueprint": ["2,2,2,4,2"]
        
}